@ECHO OFF
echo Start building program...
IF EXIST build (rd build /S /Q)
mkdir build
echo Copy database files...
xcopy db build /S /Q
echo Copy frontend files...
xcopy public build /S /Q
echo Copy configuration...
xcopy *.ini build /Q
echo Build program...
go build -o build\recorder.exe
echo done.