[main]
call_browser = true  # open browser automatically when the program starts

[dev]
debug = true
log = false
log_path = "recorder.log"  # will be ignore if "log" is false

[data]
definition_path = "definition.json"
database_path = "recorder.db"
data_path = "./data"  # data directory path

[server]
port = 50000
public_path = "./public"  # frontend resources path