CREATE TABLE IF NOT EXISTS EVENT
(
  ID              INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_ID        INTEGER NOT NULL,
  EVENT_CODE      TEXT    NOT NULL,
  START_TIMESTAMP INTEGER NOT NULL,
  STOP_TIMESTAMP  INTEGER NOT NULL,
  DESCRIPTION     NTEXT   NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS EVENT_TYPE
(
  ID          INTEGER PRIMARY KEY AUTOINCREMENT,
  DESCRIPTION NTEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS EVENT_OPTION
(
  ID          INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_ID    INTEGER NOT NULL,
  GROUP_ID    INTEGER NOT NULL,
  GROUP_TYPE  CHAR(1) NOT NULL, -- 'r' radio; 'c' check;
  DESCRIPTION NTEXT   NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS RATING
(
  ID          INTEGER PRIMARY KEY AUTOINCREMENT,
  TYPE        INTEGER NOT NULL, --1 PCL; 2 Evaluation of driver; 3 Driver emotion
  TIMESTAMP   INTEGER NOT NULL,
  RATING_LEVEL  INTEGER NOT NULL,
  DESCRIPTION TEXT    NOT NULL DEFAULT ''
);

INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (1,  'Change lanes or turn around');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (2,  'Pass or turn at an intersection');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (3,  'Wait');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (4,  'Drive or stop across the dotted line');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (5,  'Drive over or across the solid line');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (6,  'Overtake');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (7,  'Honk');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (8,  'Avoid');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (9,  'Accident');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (10, 'Parking');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (11, 'Driver''s Non-driving Behavior');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (12, 'Road signs');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (13, 'Receive an order/arrive at a boarding point');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (14, 'Passengers get on/off');
INSERT OR REPLACE INTO EVENT_TYPE (ID, DESCRIPTION) VALUES (15, 'Passengers interference');

INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (1, 1, 1, 'r', 'Change lanes to the left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (2, 1, 1, 'r', 'Change lanes to the right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (3, 1, 1, 'r', 'Turn around');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (4, 1, 2, 'c', 'No turn signal');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (5, 1, 2, 'c', 'Not following the signal lights');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (6, 1, 2, 'c', 'Wrong lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (7, 2, 1, 'r', 'Turn left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (8, 2, 1, 'r', 'Turn right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (9, 2, 1, 'r', 'Go straight');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (10, 2, 2, 'c', 'No turn signal');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (11, 2, 2, 'c', 'The actual driving direction does not match the signal lamp.');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (12, 2, 2, 'c', 'The actual driving direction does not match the lane.');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (13, 3, 1, 'c', 'Wait in the left turn lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (14, 3, 1, 'c', 'Wait in the right turn lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (15, 3, 1, 'c', 'Wait in the through lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (16, 3, 2, 'r', 'Wait at the intersection');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (17, 3, 2, 'r', 'Wait for the front U-turn car');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (18, 4, 1, 'r', 'Across the dashed line to the left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (19, 4, 1, 'r', 'Across the dotted line to the right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (20, 4, 2, 'r', 'Across white dotted line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (21, 4, 2, 'r', 'Across yellow dashed line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (22, 4, 3, 'c', 'Temporary parking on the dotted line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (23, 5, 1, 'r', 'Across the solid line to the left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (24, 5, 1, 'r', 'Across the solid line to the right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (25, 5, 2, 'r', 'Across white solid line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (26, 5, 2, 'r', 'Across yellow solid line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (27, 5, 2, 'r', 'Across double amber lines');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (28, 5, 2, 'r', 'Across the guide line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (29, 6, 1, 'r', 'Overtake on the left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (30, 6, 1, 'r', 'Overtake on the right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (31, 7, 1, 'r', 'Press the horn briefly');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (32, 7, 1, 'r', 'Press the horn long time');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (33, 7, 1, 'r', 'Press the horn briefly many times.');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (34, 7, 2, 'c', 'Honk in no-honking area');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (35, 8, 1, 'r', 'Avoid to the left');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (36, 8, 1, 'r', 'Avoid to the right');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (37, 8, 2, 'r', 'Avoid pedestrians');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (38, 8, 2, 'r', 'Avoid non-motor vehicles');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (39, 8, 2, 'r', 'Avoid motor vehicles');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (40, 8, 3, 'c', 'driver is agitated');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (41, 8, 3, 'c', 'Avoid at the entrance');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (42, 9, 1, 'r', 'This car accident');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (43, 9, 1, 'r', 'Accidents of other vehicles in same direction and same lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (44, 9, 1, 'r', 'Accidents of other vehicles in same direction and other lane');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (45, 9, 1, 'r', 'Opposite lane accident');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (46, 10, 1, 'r', 'Legal berth');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (47, 10, 1, 'r', 'Illegal berth');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (48, 10, 1, 'r', 'Parking on the road without berth');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (49, 10, 2, 'r', 'Parking crossing white solid line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (50, 10, 2, 'r', 'Parking crossing yellow solid line');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (51, 10, 2, 'r', 'Parking crossing double amber lines');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (52, 11, 1, 'r', 'Phone call');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (53, 11, 1, 'r', 'Send voice');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (54, 11, 1, 'r', 'View SMS');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (55, 11, 1, 'r', 'Typing');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (56, 11, 1, 'r', 'Smoking');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (57, 11, 1, 'r', 'listen to the music');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (58, 11, 1, 'r', 'listen to the radio');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (59, 11, 1, 'r', 'Eating');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (60, 11, 1, 'r', 'Sleeping');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (61, 11, 1, 'r', 'Other');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (62, 11, 2, 'c', 'Use Bluetooth Headset');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (63, 12, 1, 'r', 'Maximum speed limit');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (64, 12, 1, 'r', 'Minimum speed limit');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (65, 12, 1, 'r', 'Other road signs information');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (66, 13, 1, 'r', 'Receive an order');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (67, 13, 1, 'r', 'Arrive at the boarding point');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (68, 14, 1, 'r', 'Passengers get on');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (69, 14, 1, 'r', 'Passengers get off');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (70, 15, 1, 'r', 'Assist in navigation');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (71, 15, 1, 'r', 'Request');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (72, 15, 1, 'r', 'Conflict with driver');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (73, 15, 1, 'r', 'Praise the driver');
INSERT OR REPLACE INTO EVENT_OPTION (ID, EVENT_ID, GROUP_ID, GROUP_TYPE, DESCRIPTION) VALUES (74, 15, 1, 'r', 'Passengers communicate or make loud phone calls');
